#!/bin/python

import sys
from collections import Counter
    
def strings(s):
    text_val = [s[i:i+j] for j in range(1,len(s)+1) for i in range(len(s)-j+1)]
    text_val = map(''.join, map(sorted, text_val))
    words = Counter(text_val)
    return sum([(val*(val-1))/2 for each,val in words.items() if val > 1])
    

for i in range(int(raw_input())):
    text = raw_input()
    print strings(text)
